### ISSUE TITLE
Cant connect my wallet to the staking portal

### ISSUE THREAD

**Issue by kupespomana** [iotexproject/iotex-explorer#1904]
Hello,

I have created a wallet and am trying to stake it my tokens however when i try it keeps telling me ERROR please use IOPay desktop, unlock wallet. The wallet is unlocked but it doesn't connect or see it to stake my tokens.

What am i doing wrong?

**Comment by Blackpfoerd** [comment]
Same issue here.

Using MacBook Pro (2015)
MacOS Bic Sur 11.4

IoPay Wallet 1.0.15 and 1.0.16.
Used Safari, FireFox, Chrome (all latest release)

Cannot not connect Wallet to any Tool/Website in the

**Comment by denyo** [comment]
Same here. 
I got the CMC airdrop with a prestaked bucket and am unable to interact with anything in the browser.
My wallet is setup via Ledger Nano S.

Here are some logs from ioPay.
<img width="1425" alt="Bildschirmfoto 2021-09-07 um 08 04 54" src="https://user-images.githubusercontent.com/4380295/132292725-4ca83366-715f-4933-b822-ef0a3b25bad6.png">

And this is the result in the browser.
<img width="1680" alt="Bildschirmfoto 2021-09-07 um 08 14 10" src="https://user-images.githubusercontent.com/4380295/132293503-32e37e7b-e238-4c45-9c80-be9eff615c79.png">


ioPay Desktop 1.0.16.
MacOS Catalina 10.15.7
Chrome, Firefox, Safari

**Comment by ElroyLeGrande** [comment]
Same issue. What is the problem here as Ive tried everything I can think of with no success.

**Comment by negativefix** [comment]
Is there any progress on this bug? I am having the same problem with ioPay Desktop 1.0.16 on Windows 10 Pro.
![image](https://user-images.githubusercontent.com/1294467/135516847-ff1b78a5-8455-41e1-8253-2cd9d4ffa858.png)

**Comment by negativefix** [comment]
It announced on Twitter this issued has been solved. https://twitter.com/iotex_dev/status/1443738601376739329?s=21

**Comment by armadageddon** [comment]
I have this issue too and it is definitely not fixed. I also use ioPay Desktop 1.0.16 in combination with Firefox and Chrome.

**Comment by herrvaush** [comment]
This is a blocking issue for me since my iotx are on Ledger, and Ledger requires iopay desktop!
It's not acceptable that this is now open since so many months! :-(

**Comment by debra79** [comment]
i'm still having the same issue.  I created a Iopay desktop wallet version 1.0.16.  was able to stake but, now not able to sync to see my stakes.  same message... use desktop, unlock wallet, refresh.  I've done all this with no luck.  Is there something else I can try?

**Comment by herrvaush** [comment]
Hi! For me it works when using a mobile hotspot....I do not understand why though ...maybe some timing related rootcause?!RegardsMatthias 
-------- Ursprüngliche Nachricht --------Von: debra79 ***@***.***> Datum: 03.04.22  22:21  (GMT+01:00) An: iotexproject/iotex-explorer ***@***.***> Cc: herrvaush ***@***.***>, Comment ***@***.***> Betreff: Re: [iotexproject/iotex-explorer] Cant connect my wallet to the
  staking portal (#1904) 
i'm still having the same issue.  I created a Iopay desktop wallet version 1.0.16.  was able to stake but, now not able to sync to see my stakes.  same message... use desktop, unlock wallet, refresh.  I've done all this with no luck.  Is there something else I can try?
